"use client"
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import useMediaQuery from '../components/functions/MediaQuery'; 
import MenuFloatinButton from '@/components/MenuFloatingBtn';

const inter = Inter({ subsets: ['latin'] })

/*export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}*/

export default function RootLayout({ children }) {

  const isMobile = useMediaQuery('(max-width: 768px)');

  return (
    <html lang="en">
      {/*<Navbar/>*/}
      <body className={inter.className}>
      {isMobile ? "" : <Navbar/>}
      <MenuFloatinButton/>

       <div>
          {children}
       </div>

      </body>
    </html>
  )
}
